version: '3'
services:
  pipeline:
    build: .
    # Mount Google Cloud credentials for authentication
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/sa-key.json
    volumes:
      - ./sa-key.json:/tmp/sa-key.json:ro